apiVersion: apps/v1
kind: Deployment
metadata:
  name: pride-api
  labels:
    app: pride-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pride-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: pride-api
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      volumes:
        - name: application-config
          configMap:
            name: $PRIDE_CONFIG_MAP
            items:
              - key: application.yml
                path: application.yml
        - name: log-volume
          persistentVolumeClaim:
            claimName: $log_volume
      containers:
        - name: pride-api
          image: $IMAGE
          env:
            - name: JAVA_OPTS
              value: "-Dhttp.proxyHost=$http_proxy_host -Dhttp.proxyPort=$http_proxy_port -Dhttps.proxyHost=$http_proxy_host -Dhttps.proxyPort=$http_proxy_port -Dhttp.nonProxyHosts=$non_proxy_hosts"
            - name: HTTP_PROXY
              value: "http://$http_proxy_host:$http_proxy_port"
            - name: HTTPS_PROXY
              value: "http://$http_proxy_host:$http_proxy_port"
            - name: http_proxy
              value: "http://$http_proxy_host:$http_proxy_port"
            - name: https_proxy
              value: "http://$http_proxy_host:$http_proxy_port"
          ports:
            - containerPort: $port
          volumeMounts:
            - name: application-config
              mountPath: "/pride-api/config/"
              readOnly: true
            - name: log-volume
              mountPath: $logpath
          livenessProbe:
            httpGet:
              path: $context_path/actuator/health
              port: $port
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: $context_path/actuator/health
              port: $port
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pride-api-service
spec:
  selector:
    app: pride-api
  ports:
    - protocol: TCP
      port: $port
      targetPort: $port
  type: NodePort
