apiVersion: apps/v1
kind: Deployment
metadata:
  name: pride-api
  labels:
    app: pride-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pride-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: pride-api
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      volumes:
        - name: application-config
          configMap:
            name: $PRIDE_CONFIG_MAP
            items:
              - key: application.yml
                path: application.yml
        - name: filebeat-config
          configMap:
            name: $FILEBEAT_CONFIG_MAP
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: logvolume
          emptyDir: {}
      containers:
        - name: pride-api
          image: $IMAGE
          ports:
            - containerPort: $port
          volumeMounts:
            - name: application-config
              mountPath: "/pride-api/config/"
              readOnly: true
            - name: logvolume
              mountPath: $logpath
          livenessProbe:
            httpGet:
              path: /pride/ws/archive/v2/swagger-ui.html
              port: $port
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pride/ws/archive/v2/swagger-ui.html
              port: $port
            initialDelaySeconds: 60
            periodSeconds: 10
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:7.4.2
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: logvolume
              mountPath: $logpath
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
---
apiVersion: v1
kind: Service
metadata:
  name: pride-api-service
spec:
  selector:
    app: pride-api
  ports:
    - protocol: TCP
      port: $port
      targetPort: $port
  type: NodePort
