apiVersion: apps/v1
kind: Deployment
metadata:
  name: pride-api
  labels:
    app: pride-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pride-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: pride-api
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      volumes:
        - name: application-config
          configMap:
            name: $PRIDE_CONFIG_MAP
            items:
              - key: application.yml
                path: application.yml
      containers:
        - name: pride-api
          image: $IMAGE
          ports:
            - containerPort: $port
          volumeMounts:
            - name: application-config
              mountPath: "/pride-api/config/"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /pride/ws/archive/v2/swagger-ui.html
              port: $port
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pride/ws/archive/v2/swagger-ui.html
              port: $port
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pride-api-service
spec:
  selector:
    app: pride-api
  ports:
    - protocol: TCP
      port: $port
      targetPort: $port
  type: NodePort
