spring:
  application.name: $app_name
  webflux:
    base-path: $contextPath
  jackson.default-property-inclusion: NON_NULL # To avoid errors while parsing null values in objects
  codec:
    max-in-memory-size: 10MB

server:
  port: $port

app.vhost: $app_vhost

# LOGGING Properties
logging:
  path: $logspath/logs_${HOSTNAME}/
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        boot: INFO

pride-repo.api:
  baseUrl: $repo_api_base_url
  keyName: $repo_api_key_name
  keyValue: $repo_api_key_value

mongo-ws:
  baseUrl: $mongo_ws_base_url
  keyName: $mongo_ws_key_name
  keyValue: $mongo_ws_key_value

elastic-ws:
  baseUrl: $elastic_api_url
  keyName: $elastic_api_key_name
  keyValue: $elastic_api_key_value

fire:
  url: $fireUrl
  user: $fireUser
  password: $firePassword

chat-api.base-url: $chat_api_base_url
proxy-host: $http_proxy_host
proxy-port: $http_proxy_port
slack.app.token: $slack_app_token



