server:
  port: $port
  servlet.contextPath: $context_path

app.vhost: $app_vhost

# LOGGING Properties
logging:
  path: '$logpath/logs_${HOSTNAME}/'
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        boot: INFO
      apache.solr: INFO
      hibernate:
        SQL: INFO
        type.descriptor.sql.BasicBinder: INFO

# To avoid errors while parsing null values in objects
spring.jackson.default-property-inclusion: NON_NULL


# Oracle Database
spring:
  jpa.database: default
  datasource:
    continue-on-error: true
    oracle:
      jdbcUrl: $oracle_jdbc_url
      username: $oracle_username
      password: $oracle_password
      driver-class-name: oracle.jdbc.OracleDriver

# Configuration for MongoDB
mongodb:
  project:
    database: $mongodb_db
    app:
      user: $NOT_USED
      password: $NOT_USED
      authenticationDatabase: $NOT_USED
      machine.port: $NOT_USED
  projects:
    replicate:
      hosts: $NOT_USED
      ports: $NOT_USED
    single.machine.host: $NOT_USED
    machine.uri: $mongodb_machine_uri
  molecules:
    database: $mongodb_molecules_db
    machine.uri: $mongodb_molecules_machine_uri

mongo.single.machine: $NOT_USED

##### Solr CLoud #####
solr:
  master:
    hh.url: $solr_master_hh_url
    hx.url: $solr_master_hx_url
spring.data.solr.zk-host:
  hh: $solr_zk_hh
  hx: $solr_zk_hx
spring.pridedb.solr:
  hh.url: $solr_pridedb_hh_url
  hx.url: $solr_pridedb_hx_url

#aap props
aap:
  auth.url: $aap_auth_url
  domain:
    management.url: $aap_domain_management_url
    url: $aap_domain_url
  pride.service:
    uname: $aap_pride_user
    pwd: $aap_pride_passwd
jwt.certificate: $aap_jwt_cer

#email properties
spring.mail.host: smtp.ebi.ac.uk
pride.support:
  smtp.server: smtp.ebi.ac.uk
  email.address: pride-support@ebi.ac.uk

  # PRIDE urls for email sender
pride:
  url: https://www.ebi.ac.uk/pride
  archive:
    url: https://www.ebi.ac.uk/pride/archive
    help.url: https://www.ebi.ac.uk/pride/help/archive
    submission.url: https://www.ebi.ac.uk/pride/help/archive/submission
    login.url: https://www.ebi.ac.uk/pride/archive/login

twitter:
  account: https://twitter.com/pride_ebi
  num.tweets.to.show:  4
  pride:
    consumer: $NOT_USED
    consumer.secret: $NOT_USED
    token: $NOT_USED
    token.secret: $NOT_USED


#tomcat access logs
server.tomcat.accesslog:
  buffered: false
  directory: /tmp/access
  enabled: true
  file-date-format: .yyyy-MM-dd
  pattern: common
  prefix: access_log
  rotate: true
  suffix: .log


# S3 keys.
spectra.archive.s3:
  url: $s3_url
  accesskey: $s3_accesskey
  secretkey: $s3_secretkey
  bucketname: $s3_bucketname
  region: eu-west-2

cloud.aws.region.static: eu-west-2

